name: Branchlint
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint branch name
        uses: lekterable/branchlint-action@master
        with: 
          allow: |
            development
            /(fix|feat|chore)/DEV-\d{4}/
