name: Invite contributor to the organization
on: 
  push:
    branches: master
jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - uses: lekterable/inclusive-organization-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
