name: Invite

on: 
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - uses: lekterable/inclusive-organization-action@master
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          organization: just-a-test-repo
